### ISSUE TITLE
Give users the option of whether their responses are anonymous or linked to their account

### ISSUE THREAD

**Issue by Dutchman97** [r-anime/surveysite#39]
Add a checkbox to the bottom of the form where users can specify whether they want to link their account to the response so that they can easily edit their responses if necessary. Otherwise the response should be anonymous, but also have a link to edit their response. Probably also set a cookie signifying whether the user has already answered a survey if possible, to prevent duplicate responses if their response was anonymous.

**Comment by durinthal** [comment]
I've given some thought to this in other contexts and what came to mind instead of relying on a cookie (which can always be wiped client-side) is saving a hashed version of the username (for anonymization) as having taken the survey without associating it with any responses. For any user that tries to submit, check against that list first.

**Comment by eritbh** [comment]
> saving a hashed version of the username (for anonymization) as having taken the survey

I believe an older awards site used a similar strategy - usernames were hashed before being added to the database, though they were still stored alongside their responses, so it would've been possible for an admin (just me at the time) to check the salt and look up the responses of any user. I'm not sure if newer versions of the site are still doing this.

If you want to allow fully decoupling usernames from responses, it probably does make sense to introduce a second "lookup table" that stores usernames who have responded, and optionally links them to individual responses. You could optionally generate a "password" for the responses and store its hash that with the response data or in the lookup table to allow editing anonymously-submitted responses.

**Comment by Dutchman97** [comment]
Passwords will probably make things overly complicated for users, but using a table with username hash + survey ID + optional response ID columns is probably better yeah. Only downside compared to the client-based cookie approach is that it's easily possible to see whether someone responded to a certain survey, but I guess that likely won't be problematic.
