### ISSUE TITLE
e

### ISSUE THREAD

**Issue by Badspler** [r-anime/surveysite#50]
Age text box accepts the letter e. No other letters are accepted. 

Form wont submit if containing e, and tells you to fix it which is good. 

![age accepts e](https://user-images.githubusercontent.com/4272723/124740975-60016480-df6f-11eb-987d-418e627136b2.PNG)

**Comment by Dutchman97** [comment]
The input box is just a simple `<input type="number">` with no self-made validation whatsoever (on the front-end). Web browsers themselves handle validation like not being able to type in words, and being able to type `e` is just for when someone would want to type a number in scientific notation like `14e81`.

I can maybe at one point in time actually do validation on the front-end, but not in the near future
